In [2]:
import pandas as pd 
import numpy as np

In [ ]:
mis_indice = ['a','b','c']
mis_valores = [222,333,444]
mi_diccionario ={'a':222,'b':333,'c':444}

#Crear una serie con pandas 
pd.Series(mis_valores)

#index - indices de la serie 
pd.Series(data = mis_valores, index  = mis_indice)

In [ ]:
# para los diccionarios la llave seran los indices 
# de la serie 
pd.Series(mi_diccionario)

In [ ]:
s = pd.Series(data = [111,222,333,444],
                index = ['a','b','c','d'])
# index - indices
s.index 
# dttypes - tipos de datos en este caso int 
s.dtypes
# values - valores
s.values

# acceder a un elemento de la serie
s[1]
s['a']
s.loc['a']

# para acceder a mas de un elemento  
s[['a','b']]

In [ ]:
S1 = pd.Series(data = [1,2,3,4],
               index = ['d','b','c','a'])
S2 = pd.Series(data = [1,2,3,4],
               index = ['a','b','d','e'])

# suma entrada a entrada tamando en cuenta la existencia de los datos 
S1 + S2

#Promedio de los valores de la serie 
S1.mean()
#mediana 
S1.median()
#indice maximo
S1.max()
#desviacion estandar 
S1.std()
#ordena la serie apartir de los valores 
S1.sort_values()
#ordena la serie aparir de los indices 
S1.sort_index()

In [3]:
ser_height = pd.Series([165.3, 170.1, 175.0, 182.1, 168.0, 162.0, 155.2, 176.9, 178.5, 176.1,
                        167.1, 180.0, 162.2, 176.1, 158.2, 168.6, 169.2])
#las alturas estan en cm 
ser_height

# lambda funcion anonima 
# lamba trasnforma las alturas de cm a m 
ser_height.apply(lambda x : x/100)

0     1.653
1     1.701
2     1.750
3     1.821
4     1.680
5     1.620
6     1.552
7     1.769
8     1.785
9     1.761
10    1.671
11    1.800
12    1.622
13    1.761
14    1.582
15    1.686
16    1.692
dtype: float64

In [4]:
datos = {'Name':['Pako','Eduardo','Paul','Andres'],
         'Age':[24,20,25,19],
         'Gender':['M','M','M','M']}
df =  pd.DataFrame(datos)
df

      Name  Age Gender
0     Pako   24      M
1  Eduardo   20      M
2     Paul   25      M
3   Andres   19      M

In [ ]:
#Revisar 
df = pd.DataFrame(np.random.rand(10,4),
                   columns = ['A','B','C','E'])

df.head(3)

In [ ]:
df = pd.read_csv('data_studentlist.csv', header = 'infer')
#primeros 5 registros 
df.head()

In [ ]:
#ultimos 5 registros 
df.tail()

#dimension de la matriz 
forma = df.shape

In [ ]:
# obtrener el nombre de las columnas 
df.columns

#muestra una recopilacion de iformacion rapida 
df.info()

#resumen estadistico de las var numericas 
df.describe()

#muestra la columna de nombres 
df['name']

#muestra tolas las filas de las columnas indicadas 
df.loc[:,['name','gender']]

In [ ]:
#muestra la fila indicada 
df.loc[2]

In [ ]:
header = df.columns
header
#muestra todos los datos except name y gender 
df.loc[:,(header != 'name') & (header != 'gender')]

In [ ]:
#borra del documento el name y gender 
#df.drop(columns = ['name','gender'], inplace = True )

#selecciona un dato especifico 
df[(df.age > 20 ) & (df.height > 174)]

    age  grade absence bloodtype  height  weight
2    24      4       N         B   175.0    80.1
3    23      3       N        AB   182.1    85.7
7    23      1       N         A   176.9    55.0
8    23      3       N         B   178.5    64.2
9    22      2       N         B   176.1    61.3
11   22      2       N        AB   180.0    75.8
13   23      3       N         O   176.1    53.1

In [61]:
df.to_csv('modificacion.csv', header = 'infer')